import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import { Inter } from "next/font/google";
import "./globals.css";
const auth = require("@/igdb/auth");

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

auth.Authorize();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-12 z-50 absolute w-full">
          <Navbar></Navbar>
        </div>
        {children}
      </body>
    </html>
  );
}
