import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/system";
import "./globals.css";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-12 z-50 absolute w-full">
          <Navbar />
        </div>
        {await children}
        <Footer />
      </body>
    </html>
  );
}
